### ISSUE TITLE
离线签名功能 bug —— 当 keystore 中有多个钱包时

### ISSUE THREAD

**Issue by cool007zqw** [PlatONnetwork/mtool#1]
复现方式：
mtool 的 keystore 目录下有 a.json，b.json 两个钱包文件（皆非观察钱包）
现在有一个待签名的数据 unsigned.csv，该交易发送方是 a 钱包，与 b 无关

现通过 offlinesign 命令对 unsigned.csv 进行签名
该命令会读取 keystore 目录中的所有钱包文件，并要求**分别输入**每个钱包的密码

如果只输入 a 钱包的密码，而在提示输入 b 钱包密码时直接按回车或输入错误的密码，签名会成功
如果在提示输入 b 钱包密码时也**输入了正确的密码**，签名会失败。

**Comment by zhouxi-jzheng** [comment]
已接收，开发团队正在定位

**Comment by zhouxi-jzheng** [comment]
该问题已解决，当前支持当keystore目录下有多个钱包文件时，可以指定钱包输入密码进行签名交易，不论keystore目录下有多少个观察钱包，其他不相干的钱包不用输入密码。
