### ISSUE TITLE
mtool 助记词恢复私钥时，如果结尾额外带空格会导致恢复的私钥错误

### ISSUE THREAD

**Issue by qianxiaofeng** [PlatONnetwork/mtool#3]
版本 platon_mtool 1.0.0.0

复现方法
mtool account recover -m <Mnemonic><空格>

**Comment by zhouxi-jzheng** [comment]
谢谢提出问题，技术团队正在分析，若有进展会及时通知您

**Comment by zhouxi-jzheng** [comment]
@qianxiaofeng 能否给出详细的操作步骤，我们在验证过程中未能重现问题

**Comment by qianxiaofeng** [comment]
复现步骤 
- 准备好助记词 例如内容为   "word1  word2 ... wordN"
- 使用 platon_mtool account recover -m "word1  word2 ... wordN"  引号内结尾处无空格，操作后地址为 address_A
- 使用platon_mtool account recover -m "word1  word2 ... wordN  "  引号内结尾处有空格，操作后的地址为 address_B
- 对比 address_A 和 address_B  , 结果不一致

**Comment by bglmmz** [comment]
fixed. 
remove any leading and trailing whitespace, and replace multi-whitespaces with one.
